# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: usp-msg.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class HeaderMsgType(betterproto.Enum):
    ERROR = 0
    GET = 1
    GET_RESP = 2
    NOTIFY = 3
    SET = 4
    SET_RESP = 5
    OPERATE = 6
    OPERATE_RESP = 7
    ADD = 8
    ADD_RESP = 9
    DELETE = 10
    DELETE_RESP = 11
    GET_SUPPORTED_DM = 12
    GET_SUPPORTED_DM_RESP = 13
    GET_INSTANCES = 14
    GET_INSTANCES_RESP = 15
    NOTIFY_RESP = 16
    GET_SUPPORTED_PROTO = 17
    GET_SUPPORTED_PROTO_RESP = 18
    REGISTER = 19
    REGISTER_RESP = 20
    DEREGISTER = 21
    DEREGISTER_RESP = 22


class GetSupportedDMRespParamAccessType(betterproto.Enum):
    PARAM_READ_ONLY = 0
    PARAM_READ_WRITE = 1
    PARAM_WRITE_ONLY = 2


class GetSupportedDMRespObjAccessType(betterproto.Enum):
    OBJ_READ_ONLY = 0
    OBJ_ADD_DELETE = 1
    OBJ_ADD_ONLY = 2
    OBJ_DELETE_ONLY = 3


class GetSupportedDMRespParamValueType(betterproto.Enum):
    PARAM_UNKNOWN = 0
    PARAM_BASE_64 = 1
    PARAM_BOOLEAN = 2
    PARAM_DATE_TIME = 3
    PARAM_DECIMAL = 4
    PARAM_HEX_BINARY = 5
    PARAM_INT = 6
    PARAM_LONG = 7
    PARAM_STRING = 8
    PARAM_UNSIGNED_INT = 9
    PARAM_UNSIGNED_LONG = 10


class GetSupportedDMRespValueChangeType(betterproto.Enum):
    VALUE_CHANGE_UNKNOWN = 0
    VALUE_CHANGE_ALLOWED = 1
    VALUE_CHANGE_WILL_IGNORE = 2


class GetSupportedDMRespCmdType(betterproto.Enum):
    CMD_UNKNOWN = 0
    CMD_SYNC = 1
    CMD_ASYNC = 2


@dataclass
class Msg(betterproto.Message):
    header: "Header" = betterproto.message_field(1)
    body: "Body" = betterproto.message_field(2)


@dataclass
class Header(betterproto.Message):
    msg_id: str = betterproto.string_field(1)
    msg_type: "HeaderMsgType" = betterproto.enum_field(2)


@dataclass
class Body(betterproto.Message):
    request: "Request" = betterproto.message_field(1, group="msg_body")
    response: "Response" = betterproto.message_field(2, group="msg_body")
    error: "Error" = betterproto.message_field(3, group="msg_body")


@dataclass
class Request(betterproto.Message):
    get: "Get" = betterproto.message_field(1, group="req_type")
    get_supported_dm: "GetSupportedDM" = betterproto.message_field(2, group="req_type")
    get_instances: "GetInstances" = betterproto.message_field(3, group="req_type")
    set: "Set" = betterproto.message_field(4, group="req_type")
    add: "Add" = betterproto.message_field(5, group="req_type")
    delete: "Delete" = betterproto.message_field(6, group="req_type")
    operate: "Operate" = betterproto.message_field(7, group="req_type")
    notify: "Notify" = betterproto.message_field(8, group="req_type")
    get_supported_protocol: "GetSupportedProtocol" = betterproto.message_field(
        9, group="req_type"
    )
    register: "Register" = betterproto.message_field(10, group="req_type")
    deregister: "Deregister" = betterproto.message_field(11, group="req_type")


@dataclass
class Response(betterproto.Message):
    get_resp: "GetResp" = betterproto.message_field(1, group="resp_type")
    get_supported_dm_resp: "GetSupportedDMResp" = betterproto.message_field(
        2, group="resp_type"
    )
    get_instances_resp: "GetInstancesResp" = betterproto.message_field(
        3, group="resp_type"
    )
    set_resp: "SetResp" = betterproto.message_field(4, group="resp_type")
    add_resp: "AddResp" = betterproto.message_field(5, group="resp_type")
    delete_resp: "DeleteResp" = betterproto.message_field(6, group="resp_type")
    operate_resp: "OperateResp" = betterproto.message_field(7, group="resp_type")
    notify_resp: "NotifyResp" = betterproto.message_field(8, group="resp_type")
    get_supported_protocol_resp: "GetSupportedProtocolResp" = betterproto.message_field(
        9, group="resp_type"
    )
    register_resp: "RegisterResp" = betterproto.message_field(10, group="resp_type")
    deregister_resp: "DeregisterResp" = betterproto.message_field(11, group="resp_type")


@dataclass
class Error(betterproto.Message):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)
    param_errs: List["ErrorParamError"] = betterproto.message_field(3)


@dataclass
class ErrorParamError(betterproto.Message):
    param_path: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)


@dataclass
class Get(betterproto.Message):
    param_paths: List[str] = betterproto.string_field(1)
    max_depth: float = betterproto.fixed32_field(2)


@dataclass
class GetResp(betterproto.Message):
    req_path_results: List["GetRespRequestedPathResult"] = betterproto.message_field(1)


@dataclass
class GetRespRequestedPathResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)
    resolved_path_results: List["GetRespResolvedPathResult"] = (
        betterproto.message_field(4)
    )


@dataclass
class GetRespResolvedPathResult(betterproto.Message):
    resolved_path: str = betterproto.string_field(1)
    result_params: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class GetSupportedDM(betterproto.Message):
    obj_paths: List[str] = betterproto.string_field(1)
    first_level_only: bool = betterproto.bool_field(2)
    return_commands: bool = betterproto.bool_field(3)
    return_events: bool = betterproto.bool_field(4)
    return_params: bool = betterproto.bool_field(5)
    return_unique_key_sets: bool = betterproto.bool_field(6)


@dataclass
class GetSupportedDMResp(betterproto.Message):
    req_obj_results: List["GetSupportedDMRespRequestedObjectResult"] = (
        betterproto.message_field(1)
    )


@dataclass
class GetSupportedDMRespRequestedObjectResult(betterproto.Message):
    req_obj_path: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)
    data_model_inst_uri: str = betterproto.string_field(4)
    supported_objs: List["GetSupportedDMRespSupportedObjectResult"] = (
        betterproto.message_field(5)
    )


@dataclass
class GetSupportedDMRespSupportedObjectResult(betterproto.Message):
    supported_obj_path: str = betterproto.string_field(1)
    access: "GetSupportedDMRespObjAccessType" = betterproto.enum_field(2)
    is_multi_instance: bool = betterproto.bool_field(3)
    supported_commands: List["GetSupportedDMRespSupportedCommandResult"] = (
        betterproto.message_field(4)
    )
    supported_events: List["GetSupportedDMRespSupportedEventResult"] = (
        betterproto.message_field(5)
    )
    supported_params: List["GetSupportedDMRespSupportedParamResult"] = (
        betterproto.message_field(6)
    )
    divergent_paths: List[str] = betterproto.string_field(7)
    unique_key_sets: List["GetSupportedDMRespSupportedUniqueKeySet"] = (
        betterproto.message_field(8)
    )


@dataclass
class GetSupportedDMRespSupportedParamResult(betterproto.Message):
    param_name: str = betterproto.string_field(1)
    access: "GetSupportedDMRespParamAccessType" = betterproto.enum_field(2)
    value_type: "GetSupportedDMRespParamValueType" = betterproto.enum_field(3)
    value_change: "GetSupportedDMRespValueChangeType" = betterproto.enum_field(4)


@dataclass
class GetSupportedDMRespSupportedCommandResult(betterproto.Message):
    command_name: str = betterproto.string_field(1)
    input_arg_names: List[str] = betterproto.string_field(2)
    output_arg_names: List[str] = betterproto.string_field(3)
    command_type: "GetSupportedDMRespCmdType" = betterproto.enum_field(4)


@dataclass
class GetSupportedDMRespSupportedEventResult(betterproto.Message):
    event_name: str = betterproto.string_field(1)
    arg_names: List[str] = betterproto.string_field(2)


@dataclass
class GetSupportedDMRespSupportedUniqueKeySet(betterproto.Message):
    key_names: List[str] = betterproto.string_field(1)


@dataclass
class GetInstances(betterproto.Message):
    obj_paths: List[str] = betterproto.string_field(1)
    first_level_only: bool = betterproto.bool_field(2)


@dataclass
class GetInstancesResp(betterproto.Message):
    req_path_results: List["GetInstancesRespRequestedPathResult"] = (
        betterproto.message_field(1)
    )


@dataclass
class GetInstancesRespRequestedPathResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)
    curr_insts: List["GetInstancesRespCurrInstance"] = betterproto.message_field(4)


@dataclass
class GetInstancesRespCurrInstance(betterproto.Message):
    instantiated_obj_path: str = betterproto.string_field(1)
    unique_keys: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class GetSupportedProtocol(betterproto.Message):
    controller_supported_protocol_versions: str = betterproto.string_field(1)


@dataclass
class GetSupportedProtocolResp(betterproto.Message):
    agent_supported_protocol_versions: str = betterproto.string_field(1)


@dataclass
class Add(betterproto.Message):
    allow_partial: bool = betterproto.bool_field(1)
    create_objs: List["AddCreateObject"] = betterproto.message_field(2)


@dataclass
class AddCreateObject(betterproto.Message):
    obj_path: str = betterproto.string_field(1)
    param_settings: List["AddCreateParamSetting"] = betterproto.message_field(2)


@dataclass
class AddCreateParamSetting(betterproto.Message):
    param: str = betterproto.string_field(1)
    value: str = betterproto.string_field(2)
    required: bool = betterproto.bool_field(3)


@dataclass
class AddResp(betterproto.Message):
    created_obj_results: List["AddRespCreatedObjectResult"] = betterproto.message_field(
        1
    )


@dataclass
class AddRespCreatedObjectResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    oper_status: "AddRespCreatedObjectResultOperationStatus" = (
        betterproto.message_field(2)
    )


@dataclass
class AddRespCreatedObjectResultOperationStatus(betterproto.Message):
    oper_failure: "AddRespCreatedObjectResultOperationStatusOperationFailure" = (
        betterproto.message_field(1, group="oper_status")
    )
    oper_success: "AddRespCreatedObjectResultOperationStatusOperationSuccess" = (
        betterproto.message_field(2, group="oper_status")
    )


@dataclass
class AddRespCreatedObjectResultOperationStatusOperationFailure(betterproto.Message):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)


@dataclass
class AddRespCreatedObjectResultOperationStatusOperationSuccess(betterproto.Message):
    instantiated_path: str = betterproto.string_field(1)
    param_errs: List["AddRespParameterError"] = betterproto.message_field(2)
    unique_keys: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class AddRespParameterError(betterproto.Message):
    param: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)


@dataclass
class Delete(betterproto.Message):
    allow_partial: bool = betterproto.bool_field(1)
    obj_paths: List[str] = betterproto.string_field(2)


@dataclass
class DeleteResp(betterproto.Message):
    deleted_obj_results: List["DeleteRespDeletedObjectResult"] = (
        betterproto.message_field(1)
    )


@dataclass
class DeleteRespDeletedObjectResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    oper_status: "DeleteRespDeletedObjectResultOperationStatus" = (
        betterproto.message_field(2)
    )


@dataclass
class DeleteRespDeletedObjectResultOperationStatus(betterproto.Message):
    oper_failure: "DeleteRespDeletedObjectResultOperationStatusOperationFailure" = (
        betterproto.message_field(1, group="oper_status")
    )
    oper_success: "DeleteRespDeletedObjectResultOperationStatusOperationSuccess" = (
        betterproto.message_field(2, group="oper_status")
    )


@dataclass
class DeleteRespDeletedObjectResultOperationStatusOperationFailure(betterproto.Message):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)


@dataclass
class DeleteRespDeletedObjectResultOperationStatusOperationSuccess(betterproto.Message):
    affected_paths: List[str] = betterproto.string_field(1)
    unaffected_path_errs: List["DeleteRespUnaffectedPathError"] = (
        betterproto.message_field(2)
    )


@dataclass
class DeleteRespUnaffectedPathError(betterproto.Message):
    unaffected_path: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)


@dataclass
class Set(betterproto.Message):
    allow_partial: bool = betterproto.bool_field(1)
    update_objs: List["SetUpdateObject"] = betterproto.message_field(2)


@dataclass
class SetUpdateObject(betterproto.Message):
    obj_path: str = betterproto.string_field(1)
    param_settings: List["SetUpdateParamSetting"] = betterproto.message_field(2)


@dataclass
class SetUpdateParamSetting(betterproto.Message):
    param: str = betterproto.string_field(1)
    value: str = betterproto.string_field(2)
    required: bool = betterproto.bool_field(3)


@dataclass
class SetResp(betterproto.Message):
    updated_obj_results: List["SetRespUpdatedObjectResult"] = betterproto.message_field(
        1
    )


@dataclass
class SetRespUpdatedObjectResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    oper_status: "SetRespUpdatedObjectResultOperationStatus" = (
        betterproto.message_field(2)
    )


@dataclass
class SetRespUpdatedObjectResultOperationStatus(betterproto.Message):
    oper_failure: "SetRespUpdatedObjectResultOperationStatusOperationFailure" = (
        betterproto.message_field(1, group="oper_status")
    )
    oper_success: "SetRespUpdatedObjectResultOperationStatusOperationSuccess" = (
        betterproto.message_field(2, group="oper_status")
    )


@dataclass
class SetRespUpdatedObjectResultOperationStatusOperationFailure(betterproto.Message):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)
    updated_inst_failures: List["SetRespUpdatedInstanceFailure"] = (
        betterproto.message_field(3)
    )


@dataclass
class SetRespUpdatedObjectResultOperationStatusOperationSuccess(betterproto.Message):
    updated_inst_results: List["SetRespUpdatedInstanceResult"] = (
        betterproto.message_field(1)
    )


@dataclass
class SetRespUpdatedInstanceFailure(betterproto.Message):
    affected_path: str = betterproto.string_field(1)
    param_errs: List["SetRespParameterError"] = betterproto.message_field(2)


@dataclass
class SetRespUpdatedInstanceResult(betterproto.Message):
    affected_path: str = betterproto.string_field(1)
    param_errs: List["SetRespParameterError"] = betterproto.message_field(2)
    updated_params: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class SetRespParameterError(betterproto.Message):
    param: str = betterproto.string_field(1)
    err_code: float = betterproto.fixed32_field(2)
    err_msg: str = betterproto.string_field(3)


@dataclass
class Operate(betterproto.Message):
    command: str = betterproto.string_field(1)
    command_key: str = betterproto.string_field(2)
    send_resp: bool = betterproto.bool_field(3)
    input_args: Dict[str, str] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class OperateResp(betterproto.Message):
    operation_results: List["OperateRespOperationResult"] = betterproto.message_field(1)


@dataclass
class OperateRespOperationResult(betterproto.Message):
    executed_command: str = betterproto.string_field(1)
    req_obj_path: str = betterproto.string_field(2, group="operation_resp")
    req_output_args: "OperateRespOperationResultOutputArgs" = betterproto.message_field(
        3, group="operation_resp"
    )
    cmd_failure: "OperateRespOperationResultCommandFailure" = betterproto.message_field(
        4, group="operation_resp"
    )


@dataclass
class OperateRespOperationResultOutputArgs(betterproto.Message):
    output_args: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class OperateRespOperationResultCommandFailure(betterproto.Message):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)


@dataclass
class Notify(betterproto.Message):
    subscription_id: str = betterproto.string_field(1)
    send_resp: bool = betterproto.bool_field(2)
    event: "NotifyEvent" = betterproto.message_field(3, group="notification")
    value_change: "NotifyValueChange" = betterproto.message_field(
        4, group="notification"
    )
    obj_creation: "NotifyObjectCreation" = betterproto.message_field(
        5, group="notification"
    )
    obj_deletion: "NotifyObjectDeletion" = betterproto.message_field(
        6, group="notification"
    )
    oper_complete: "NotifyOperationComplete" = betterproto.message_field(
        7, group="notification"
    )
    on_board_req: "NotifyOnBoardRequest" = betterproto.message_field(
        8, group="notification"
    )


@dataclass
class NotifyEvent(betterproto.Message):
    obj_path: str = betterproto.string_field(1)
    event_name: str = betterproto.string_field(2)
    params: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class NotifyValueChange(betterproto.Message):
    param_path: str = betterproto.string_field(1)
    param_value: str = betterproto.string_field(2)


@dataclass
class NotifyObjectCreation(betterproto.Message):
    obj_path: str = betterproto.string_field(1)
    unique_keys: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class NotifyObjectDeletion(betterproto.Message):
    obj_path: str = betterproto.string_field(1)


@dataclass
class NotifyOperationComplete(betterproto.Message):
    obj_path: str = betterproto.string_field(1)
    command_name: str = betterproto.string_field(2)
    command_key: str = betterproto.string_field(3)
    req_output_args: "NotifyOperationCompleteOutputArgs" = betterproto.message_field(
        4, group="operation_resp"
    )
    cmd_failure: "NotifyOperationCompleteCommandFailure" = betterproto.message_field(
        5, group="operation_resp"
    )


@dataclass
class NotifyOperationCompleteOutputArgs(betterproto.Message):
    output_args: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class NotifyOperationCompleteCommandFailure(betterproto.Message):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)


@dataclass
class NotifyOnBoardRequest(betterproto.Message):
    oui: str = betterproto.string_field(1)
    product_class: str = betterproto.string_field(2)
    serial_number: str = betterproto.string_field(3)
    agent_supported_protocol_versions: str = betterproto.string_field(4)


@dataclass
class NotifyResp(betterproto.Message):
    subscription_id: str = betterproto.string_field(1)


@dataclass
class Register(betterproto.Message):
    allow_partial: bool = betterproto.bool_field(1)
    reg_paths: List["RegisterRegistrationPath"] = betterproto.message_field(2)


@dataclass
class RegisterRegistrationPath(betterproto.Message):
    path: str = betterproto.string_field(1)


@dataclass
class RegisterResp(betterproto.Message):
    registered_path_results: List["RegisterRespRegisteredPathResult"] = (
        betterproto.message_field(1)
    )


@dataclass
class RegisterRespRegisteredPathResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    oper_status: "RegisterRespRegisteredPathResultOperationStatus" = (
        betterproto.message_field(2)
    )


@dataclass
class RegisterRespRegisteredPathResultOperationStatus(betterproto.Message):
    oper_failure: "RegisterRespRegisteredPathResultOperationStatusOperationFailure" = (
        betterproto.message_field(1, group="oper_status")
    )
    oper_success: "RegisterRespRegisteredPathResultOperationStatusOperationSuccess" = (
        betterproto.message_field(2, group="oper_status")
    )


@dataclass
class RegisterRespRegisteredPathResultOperationStatusOperationFailure(
    betterproto.Message
):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)


@dataclass
class RegisterRespRegisteredPathResultOperationStatusOperationSuccess(
    betterproto.Message
):
    registered_path: str = betterproto.string_field(1)


@dataclass
class Deregister(betterproto.Message):
    paths: List[str] = betterproto.string_field(1)


@dataclass
class DeregisterResp(betterproto.Message):
    deregistered_path_results: List["DeregisterRespDeregisteredPathResult"] = (
        betterproto.message_field(1)
    )


@dataclass
class DeregisterRespDeregisteredPathResult(betterproto.Message):
    requested_path: str = betterproto.string_field(1)
    oper_status: "DeregisterRespDeregisteredPathResultOperationStatus" = (
        betterproto.message_field(2)
    )


@dataclass
class DeregisterRespDeregisteredPathResultOperationStatus(betterproto.Message):
    oper_failure: (
        "DeregisterRespDeregisteredPathResultOperationStatusOperationFailure"
    ) = betterproto.message_field(1, group="oper_status")
    oper_success: (
        "DeregisterRespDeregisteredPathResultOperationStatusOperationSuccess"
    ) = betterproto.message_field(2, group="oper_status")


@dataclass
class DeregisterRespDeregisteredPathResultOperationStatusOperationFailure(
    betterproto.Message
):
    err_code: float = betterproto.fixed32_field(1)
    err_msg: str = betterproto.string_field(2)


@dataclass
class DeregisterRespDeregisteredPathResultOperationStatusOperationSuccess(
    betterproto.Message
):
    deregistered_path: List[str] = betterproto.string_field(1)
