# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: usp-record.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class RecordPayloadSecurity(betterproto.Enum):
    PLAINTEXT = 0
    TLS12 = 1


class SessionContextRecordPayloadSARState(betterproto.Enum):
    NONE = 0
    BEGIN = 1
    INPROCESS = 2
    COMPLETE = 3


class MQTTConnectRecordMQTTVersion(betterproto.Enum):
    V3_1_1 = 0
    V5 = 1


class STOMPConnectRecordSTOMPVersion(betterproto.Enum):
    V1_2 = 0


@dataclass
class Record(betterproto.Message):
    version: str = betterproto.string_field(1)
    to_id: str = betterproto.string_field(2)
    from_id: str = betterproto.string_field(3)
    payload_security: "RecordPayloadSecurity" = betterproto.enum_field(4)
    mac_signature: bytes = betterproto.bytes_field(5)
    sender_cert: bytes = betterproto.bytes_field(6)
    no_session_context: "NoSessionContextRecord" = betterproto.message_field(
        7, group="record_type"
    )
    session_context: "SessionContextRecord" = betterproto.message_field(
        8, group="record_type"
    )
    websocket_connect: "WebSocketConnectRecord" = betterproto.message_field(
        9, group="record_type"
    )
    mqtt_connect: "MQTTConnectRecord" = betterproto.message_field(
        10, group="record_type"
    )
    stomp_connect: "STOMPConnectRecord" = betterproto.message_field(
        11, group="record_type"
    )
    disconnect: "DisconnectRecord" = betterproto.message_field(12, group="record_type")
    uds_connect: "UDSConnectRecord" = betterproto.message_field(13, group="record_type")


@dataclass
class NoSessionContextRecord(betterproto.Message):
    payload: bytes = betterproto.bytes_field(2)


@dataclass
class SessionContextRecord(betterproto.Message):
    session_id: int = betterproto.uint64_field(1)
    sequence_id: int = betterproto.uint64_field(2)
    expected_id: int = betterproto.uint64_field(3)
    retransmit_id: int = betterproto.uint64_field(4)
    payload_sar_state: "SessionContextRecordPayloadSARState" = betterproto.enum_field(5)
    payloadrec_sar_state: "SessionContextRecordPayloadSARState" = (
        betterproto.enum_field(6)
    )
    payload: List[bytes] = betterproto.bytes_field(7)


@dataclass
class WebSocketConnectRecord(betterproto.Message):
    pass


@dataclass
class MQTTConnectRecord(betterproto.Message):
    version: "MQTTConnectRecordMQTTVersion" = betterproto.enum_field(1)
    subscribed_topic: str = betterproto.string_field(2)


@dataclass
class STOMPConnectRecord(betterproto.Message):
    version: "STOMPConnectRecordSTOMPVersion" = betterproto.enum_field(1)
    subscribed_destination: str = betterproto.string_field(2)


@dataclass
class UDSConnectRecord(betterproto.Message):
    pass


@dataclass
class DisconnectRecord(betterproto.Message):
    reason: str = betterproto.string_field(1)
    reason_code: float = betterproto.fixed32_field(2)
